{
    "data": "/lus/gila/projects/candle_aesp_CNDA/avasan/RL_Workflows/RL_DPO/pref-opt-for-mols/MolFormer_Class/models_for_archit/data/hepa.csv",
    "smiles_col": "SMILES",
    "label_col": "label",
    "pos_label": 1,
    "neg_label": 0,
    "scaffolds_sampling": "data/rtcb_scaffolds.smi",
    "batch_sample": 16,
    "out_dir": "out/",
    "out_pattern": "hepa",
    "evaluator_type": "molformer_tox",
    "evaluator_config":"/lus/gila/projects/candle_aesp_CNDA/avasan/RL_Workflows/RL_DPO/pref-opt-for-mols/MolFormer_Class/models_for_archit/yaml_files/hepa.yaml",
    "evaluator_checkpoint": "/lus/gila/projects/candle_aesp_CNDA/avasan/RL_Workflows/RL_DPO/pref-opt-for-mols/MolFormer_Class/models_for_archit/best_model_weights/hepa_weights_ftpubmqj.pt",
    "loop_number": 5,
    "goal_ratio": 0.8,
    "device": 0 }
